version:  "3.9"

services: 
    app:
      build:
        context: ./app
      restart: always
      volumes:
        - static-data:/vol/static

    nginx:
      build: 
        context: ./nginx
      restart: always
      ports:
        - 80:80
      depends_on: 
        - app
      volumes:
        - static-data:/vol/static

volumes:
  static-data: