version: "3.9"

services:
  web:
    build: .
    environment:
      - PYTHONUNBUFFERED=0
      - PYTHONDONTWRITEBYTECODE=1
    ports:
      - "5000:5000"
    volumes:
      - /opt/rsecdotcom:/rsecdotcom
    container_name: "rsec_main_website"